### ISSUE TITLE
esptouchResult for multidevice

### ISSUE THREAD

**Issue by partylover** [lou-lan/SmartConfig#2]
I have 2 ESP32
I want the Smart config for swift to be able to set up multiple devices and have a detailed reply. Same as in Objective-C.

Please, how should I write an Array in Swift? This will work like obj-c.

```
func executeForResult() -> ESPTouchResult {
        // 同步锁
        condition.lock()
        // 获得配置所需要的参数
        esptouchTask = ESPTouchTask(apSsid: SSID, andApBssid: BSSID, andApPwd: PASS)
        // 设置代理
        esptouchTask.setEsptouchDelegate(esptouchDelegate)
        condition.unlock()
        let esptouchResult: ESPTouchResult = self.esptouchTask.executeForResult()
        print("⭕️\(esptouchResult)")
        return esptouchResult
    }
```
**Output Swift**
`⭕️[isSuc: YES,isCancelled: NO,bssid: 240ac41000e4,inetAddress: 192.168.1.4]`

-----------------------------------------------------------------------------------------------------
**Objective-C**
```
- (NSArray *) executeForResults
{
    [self._condition lock];
    NSString *apSsid = self.ssidLabel.text;
    NSString *apPwd = self._pwdTextView.text;
    NSString *apBssid = self.bssid;
    int taskCount = [self._taskResultCountTextView.text intValue];
    BOOL useAES = NO;
    if (useAES) {
        NSString *secretKey = @"1234567890123456"; // TODO modify your own key
        ESPAES *aes = [[ESPAES alloc] initWithKey:secretKey];
        self._esptouchTask = [[ESPTouchTask alloc]initWithApSsid:apSsid andApBssid:apBssid andApPwd:apPwd andAES:aes];
    } else {
        self._esptouchTask = [[ESPTouchTask alloc]initWithApSsid:apSsid andApBssid:apBssid andApPwd:apPwd];
    }
    
    // set delegate
    [self._esptouchTask setEsptouchDelegate:self._esptouchDelegate];
    [self._condition unlock];
    NSArray * esptouchResults = [self._esptouchTask executeForResults:taskCount];
    NSLog(@"ESPViewController executeForResult() result is: %@",esptouchResults);
    return esptouchResults;
}
```

**Output Obj-C**
```
ESPViewController executeForResult() result is: (
    "[isSuc: YES,isCancelled: NO,bssid: 240ac41000e4,inetAddress: 192.168.1.4]",
    "[isSuc: YES,isCancelled: NO,bssid: b4e62dc84e71,inetAddress: 192.168.1.6]"
)
```

**Comment by lou-lan** [comment]
The ability to configure multiple devices appears to be canceled in the new library. You can look at this repository https://github.com/EspressifApp/EsptouchForIOS, but this is an Objective-C project.

```Swift
func executeForResults() -> [Any]? {
    condition.lock()
    let apSsid = ssidLabel.text
    let apPwd = pwdTextView.text
    let apBssid = bssid
    let taskCount: Int = taskResultCountTextView.text
    let useAES = false
    if useAES {
        let secretKey = "1234567890123456"
            // TODO modify your own key
        let aes = ESPAES(key: NSDraggingItem.ImageComponentKey(secretKey))
        esptouchTask = ESPTouchTask(apSsid: apSsid, andApBssid: apBssid, andApPwd: apPwd, andAES: aes)
    } else {
        esptouchTask = ESPTouchTask(apSsid: apSsid, andApBssid: apBssid, andApPwd: apPwd)
    }
    // set delegate
    esptouchTask.esptouchDelegate = esptouchDelegate
    condition.unlock()
    let esptouchResults = esptouchTask.execute(forResults: taskCount)
    print("ESPViewController executeForResult() result is: \(esptouchResults)")
    return esptouchResults
}
```

**Comment by partylover** [comment]
Thank you very much for the answer.
Wait a minute, I'll go back and test it.

**Comment by dilip907** [comment]
Hi Team,
I have tried connect with iOS 12.4 but its always return fail.
Getting response every time 
[isSuc: NO,isCancelled: NO,bssid: (null),inetAddress: (null)]

Could you please help me what I am doing wrong.

I am using same 
func executeForResult() -> ESPTouchResult {
        // 同步锁
        condition.lock()
        // 获得配置所需要的参数
        esptouchTask = ESPTouchTask(apSsid: SSID, andApBssid: BSSID, andApPwd: PASS)
        // 设置代理
        esptouchTask.setEsptouchDelegate(esptouchDelegate)
        condition.unlock()
        let esptouchResult: ESPTouchResult = self.esptouchTask.executeForResult()
        print("⭕️\(esptouchResult)")
        return esptouchResult
    }

OUTPUT 
[isSuc: NO,isCancelled: NO,bssid: (null),inetAddress: (null)]


Thanks

**Comment by dilip907** [comment]
@lou-lan 
Can you please help me what I am doing wrong or I missed any configuration I have tried provided by your demo and tried many demos but every time getting same.

Here is my output 
[isSuc: NO,isCancelled: NO,bssid: (null),inetAddress: (null)]
Thanks

**Comment by lou-lan** [comment]
@dilip907 Make sure your hardware device is in listening mode.

**Comment by dilip907** [comment]
@lou-lan Thanks for your valuable reply.
Need to any configuration for listing mode ?
I have tested iPhone SE and tested iPhone6 (12.3.1) its not working.

**Comment by lou-lan** [comment]
Sorry for the late reply, the hardware refers to esp8266 wifi chip.
Example: [wifistartsmart](https://nodemcu.readthedocs.io/en/master/modules/wifi/#wifistartsmart)

**Comment by dilip907** [comment]
its Okay.
@lou-lan Thank you so much for your great support.I will check link shared by you.

**Comment by dilip907** [comment]
@lou-lan  WIFI_SMART_ENABLE  property is not there 
https://github.com/lou-lan/SmartConfig
https://github.com/EspressifApp/EsptouchForIOS/
I have check both demos.
